services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Gmbit\Simple\:
    resource: '../Classes/*'
  Psr\Log\LoggerInterface:
    factory: ['TYPO3\CMS\Core\Log\LogManager', 'getLogger']
    arguments:
      - 'Gmbit\Simple\Controller\MemberController'
